package vista;

import controlador.Hilo;
import controlador.InteraccionUI;
import controlador.PreparacionJuego;
import javax.swing.JOptionPane;

/**
 *
 * @author Angelo
 */
public class frmJuego extends javax.swing.JFrame {

    //Creamos referencias
    PreparacionJuego prepjuego = new PreparacionJuego();
    InteraccionUI interUI = new InteraccionUI();
    Hilo hilo = new Hilo(this);
    //Variables de apoyo
    public boolean test = true;

    public frmJuego() {
        //Preparacion.lblNumRondaP.setText(lblNumRonda.getText());
        initComponents();
        //  setSize(1876, 1060); //Tamaño del frame
        setResizable(false); //Para no poder extender al frame
        setLocationRelativeTo(null); //Para que se muestre centrado
        lblNumRonda.setText("1"); //Colocamos en número de ronda
        btnOcultarTropas.setVisible(false); //Colocamos invisible el botón de ocultar tropas
        lblCantidadTropas.setText(String.valueOf(Integer.parseInt(lblNumRonda.getText()) + 4)); //Colocamos la cantidad de tropas usables
        prepjuego.RandomCPU(1);//Creamos la pila del CPU
        btnIniciar.setEnabled(lblCantidadTropas.getText().equals("0")); //Para que el boton de iniciar se muestre deshablitdo
        prepjuego.lista(); //Listamos la pila del CPU

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNRonda = new javax.swing.JLabel();
        lblNumRonda = new javax.swing.JLabel();
        lblTropaPlayer1 = new javax.swing.JLabel();
        lblTropa1CPU = new javax.swing.JLabel();
        lblCastilloCPU = new javax.swing.JLabel();
        lblCastilloPlayer = new javax.swing.JLabel();
        lblVidasCpu = new javax.swing.JLabel();
        lblVidasPlayer = new javax.swing.JLabel();
        lblCorazonCpu = new javax.swing.JLabel();
        lblCorazonPlayer = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnMostrarTropas = new javax.swing.JButton();
        btnOcultarTropas = new javax.swing.JButton();
        lblTextTropasRestantes1 = new javax.swing.JLabel();
        lblMagoUI = new javax.swing.JLabel();
        lblArqueraUI = new javax.swing.JLabel();
        lblCPU1 = new javax.swing.JLabel();
        lblCaballero = new javax.swing.JLabel();
        lblTextTropasRestantes = new javax.swing.JLabel();
        lblCantidadTropas = new javax.swing.JLabel();
        lblCPU2 = new javax.swing.JLabel();
        lblCPU3 = new javax.swing.JLabel();
        lblTextCamino = new javax.swing.JLabel();
        lblMapa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1876, 1054));
        setMinimumSize(new java.awt.Dimension(1876, 1054));
        setPreferredSize(new java.awt.Dimension(1876, 1054));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNRonda.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        lblNRonda.setText("N° Ronda:");
        getContentPane().add(lblNRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));

        lblNumRonda.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        lblNumRonda.setText("1");
        getContentPane().add(lblNumRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, 40));
        getContentPane().add(lblTropaPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 515, -1, -1));
        getContentPane().add(lblTropa1CPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 515, -1, -1));

        lblCastilloCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Castillo-rojo-x307.png"))); // NOI18N
        getContentPane().add(lblCastilloCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        lblCastilloPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Castillo-verde-x307.png"))); // NOI18N
        getContentPane().add(lblCastilloPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 360, -1, -1));

        lblVidasCpu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVidasCpu.setForeground(new java.awt.Color(255, 255, 255));
        lblVidasCpu.setText("10");
        lblVidasCpu.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblVidasCpuPropertyChange(evt);
            }
        });
        getContentPane().add(lblVidasCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 314, -1, -1));

        lblVidasPlayer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVidasPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblVidasPlayer.setText("10");
        lblVidasPlayer.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblVidasPlayerPropertyChange(evt);
            }
        });
        getContentPane().add(lblVidasPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1415, 314, -1, -1));

        lblCorazonCpu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCorazonCpu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Corazon.png"))); // NOI18N
        lblCorazonCpu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblCorazonCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 300, -1, -1));

        lblCorazonPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Corazon.png"))); // NOI18N
        getContentPane().add(lblCorazonPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1394, 300, -1, -1));

        btnIniciar.setBackground(new java.awt.Color(109, 160, 79));
        btnIniciar.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("INICIAR");
        btnIniciar.setBorder(null);
        btnIniciar.setBorderPainted(false);
        btnIniciar.setContentAreaFilled(false);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1642, 940, 190, 50));

        btnMostrarTropas.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnMostrarTropas.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarTropas.setText("VER TROPAS");
        btnMostrarTropas.setBorder(null);
        btnMostrarTropas.setBorderPainted(false);
        btnMostrarTropas.setContentAreaFilled(false);
        btnMostrarTropas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTropasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarTropas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1642, 863, 190, 50));

        btnOcultarTropas.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        btnOcultarTropas.setForeground(new java.awt.Color(255, 255, 255));
        btnOcultarTropas.setText("Ocultar");
        btnOcultarTropas.setBorder(null);
        btnOcultarTropas.setBorderPainted(false);
        btnOcultarTropas.setContentAreaFilled(false);
        btnOcultarTropas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcultarTropasActionPerformed(evt);
            }
        });
        getContentPane().add(btnOcultarTropas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1642, 863, 190, 50));

        lblTextTropasRestantes1.setBackground(new java.awt.Color(255, 255, 255));
        lblTextTropasRestantes1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        lblTextTropasRestantes1.setForeground(new java.awt.Color(255, 255, 255));
        lblTextTropasRestantes1.setText("TROPAS ENEMIGAS");
        getContentPane().add(lblTextTropasRestantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 712, -1, -1));

        lblMagoUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mago-Verde-UI.png"))); // NOI18N
        lblMagoUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMagoUIMouseClicked(evt);
            }
        });
        getContentPane().add(lblMagoUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 130, -1, -1));

        lblArqueraUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Arquera-Verde-UI.png"))); // NOI18N
        lblArqueraUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArqueraUIMouseClicked(evt);
            }
        });
        getContentPane().add(lblArqueraUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 320, -1, -1));
        getContentPane().add(lblCPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 765, -1, -1));

        lblCaballero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caballero-Verde-UI.png"))); // NOI18N
        lblCaballero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCaballeroMouseClicked(evt);
            }
        });
        getContentPane().add(lblCaballero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 520, -1, -1));

        lblTextTropasRestantes.setBackground(new java.awt.Color(255, 255, 255));
        lblTextTropasRestantes.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        lblTextTropasRestantes.setForeground(new java.awt.Color(255, 255, 255));
        lblTextTropasRestantes.setText("TROPAS RESTANTES:");
        getContentPane().add(lblTextTropasRestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1655, 26, -1, -1));

        lblCantidadTropas.setBackground(new java.awt.Color(255, 255, 255));
        lblCantidadTropas.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        lblCantidadTropas.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadTropas.setText("1");
        lblCantidadTropas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblCantidadTropasPropertyChange(evt);
            }
        });
        getContentPane().add(lblCantidadTropas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1805, 23, 20, -1));
        getContentPane().add(lblCPU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 765, -1, -1));
        getContentPane().add(lblCPU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 765, -1, -1));

        lblTextCamino.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        lblTextCamino.setForeground(new java.awt.Color(255, 255, 255));
        lblTextCamino.setText("Seleccione LA TROPA");
        getContentPane().add(lblTextCamino, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 80, -1, -1));

        lblMapa.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        lblMapa.setForeground(new java.awt.Color(255, 255, 255));
        lblMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TowerDefence.jpg"))); // NOI18N
        getContentPane().add(lblMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVidasCpuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblVidasCpuPropertyChange
        if (Double.parseDouble(lblVidasCpu.getText()) <= 0.0) {//Verificamos los cambios del lblVida y esperamos a que sea 0.0 o menos
            new frmGanador().setVisible(true); //Colocamos visible el ganador
            this.dispose(); //Ocultamos la pantalla actual
            hilo.interrupt(); //Detenemos por completo el hilo
        }
    }//GEN-LAST:event_lblVidasCpuPropertyChange

    private void lblMagoUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMagoUIMouseClicked
        if (!lblCantidadTropas.getText().equals("0")) { //Verificamos si podemos colocar tropas
            prepjuego.AgregarTropaUI(Integer.valueOf(lblCantidadTropas.getText()),
                    Integer.valueOf(lblNumRonda.getText()),
                    "1", 1, 1.5, "/img/Mago-Verde-x54.png"); //Agregamos Mago con los parametros
        } else {
            JOptionPane.showMessageDialog(null, 
                    "Ha alcanzado el máximo de tropas por ronda", 
                    "ALERTA", JOptionPane.WARNING_MESSAGE); //Mensaje de alerta debido a que no se pueden colocar tropas
        }        
    }//GEN-LAST:event_lblMagoUIMouseClicked

    private void lblArqueraUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArqueraUIMouseClicked
        if (!lblCantidadTropas.getText().equals("0")) {
            prepjuego.AgregarTropaUI(Integer.valueOf(lblCantidadTropas.getText()),
                    Integer.valueOf(lblNumRonda.getText()),
                    "1", 2, 1.0, "/img/Arquera-Verde-x59.png"); //Agregamos Arquera con los parametros

        } else {
            JOptionPane.showMessageDialog(null, 
                    "Ha alcanzado el máximo de tropas por ronda", 
                    "ALERTA", JOptionPane.WARNING_MESSAGE); //Mensaje de alerta debido a que no se pueden colocar tropas
        }
    }//GEN-LAST:event_lblArqueraUIMouseClicked

    private void lblCaballeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCaballeroMouseClicked
        if (!lblCantidadTropas.getText().equals("0"))
            prepjuego.AgregarTropaUI(Integer.valueOf(lblCantidadTropas.getText()),
                    Integer.valueOf(lblNumRonda.getText()),
                    "1", 3, 2.0, "/img/caballero-Verde-85x90.png"); //Agregamos Caballero con los parametros
        else {
            JOptionPane.showMessageDialog(null, 
                    "Ha alcanzado el máximo de tropas por ronda", 
                    "ALERTA", JOptionPane.WARNING_MESSAGE);//Mensaje de alerta debido a que no se pueden colocar tropas
        }
    }//GEN-LAST:event_lblCaballeroMouseClicked

    private void btnMostrarTropasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTropasActionPerformed
        prepjuego.MostrarTropasCPU(); //Muestra las tropas del CPU
        //   prepjuego.lista();
        btnMostrarTropas.setVisible(false); //Oculta el botón de ver tropas
        btnOcultarTropas.setVisible(true); //Coloca visible el botón de Ocultar
        //Coloca los lbl Visibles
        lblCPU1.setVisible(true);
        lblCPU2.setVisible(true);
        lblCPU3.setVisible(true);
    }//GEN-LAST:event_btnMostrarTropasActionPerformed

    private void btnOcultarTropasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcultarTropasActionPerformed
        btnOcultarTropas.setVisible(false); //Oculta las tropas del CPU
        //Coloca los lbl invisibles
        lblCPU1.setVisible(false);
        lblCPU2.setVisible(false);
        lblCPU3.setVisible(false);
        btnMostrarTropas.setVisible(true); //Pone visible el botón de ver tropas
    }//GEN-LAST:event_btnOcultarTropasActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        prepjuego.ActualizarIconoCam(); //Actualiza los iconos

        if (test) { //Valida si podemos iniciar el hilo por primera vez
            hilo.start(); //Inicia el hilo
            test = false; //Cambia el estado para evitar iniciarlo varias veces

        } else {
            hilo = new Hilo(this); //Cre un nuevo hilo
            hilo.start(); //Incia el hilo
            prepjuego.ActualizarIconoIncial(); //Actualiza los iconos al inicio
        }
        //Coloca Visible las tropas
        lblTropa1CPU.setVisible(true);
        lblTropaPlayer1.setVisible(true);
        //Inactiva los botones
        btnIniciar.setEnabled(false);
        btnMostrarTropas.setEnabled(false);
        btnOcultarTropas.setEnabled(false);

    }//GEN-LAST:event_btnIniciarActionPerformed

    private void lblCantidadTropasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblCantidadTropasPropertyChange
        if (lblCantidadTropas.getText().equals("0")) { //Verifica si no hay tropas disponibles
            btnIniciar.setEnabled(true); //Activa el botón de inicio
        }
    }//GEN-LAST:event_lblCantidadTropasPropertyChange

    private void lblVidasPlayerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblVidasPlayerPropertyChange
        if (Double.parseDouble(lblVidasPlayer.getText()) <= 0.0) { //Verifica si la vida es 0.0 o menor
            new frmPerdedor().setVisible(true); //Abre pantalla de perdedor
            this.dispose(); //Cierra la ventana actual
            hilo.interrupt(); //Cierra el hilo
        }
    }//GEN-LAST:event_lblVidasPlayerPropertyChange

    public void interCastillo() {
        if (prepjuego.verificaDueloCastillo() == 1) { //Verifia el castillo donde sucede
            prepjuego.getCastilloPlayer().setVida(
                    prepjuego.getCastilloPlayer().getVida() - prepjuego.DevolverDanio(1)); //Reduce la vida del castillo
            interUI.ActualizaVidaCastillos(
                    1, prepjuego.getCastilloPlayer().getVida()); //Actualiza la vida del castillo
            prepjuego.EliminarTropaCastillo(1); 
            prepjuego.ReiniciaPosicionesCam();
            prepjuego.ActualizarIconoCam();
        }
        if (prepjuego.verificaDueloCastillo() == 2) {
            prepjuego.getCastilloCPU().setVida(
                    prepjuego.getCastilloCPU().getVida() - prepjuego.DevolverDanio(2)); //Reduce la vida del castillo
            interUI.ActualizaVidaCastillos(
                    2, prepjuego.getCastilloCPU().getVida()); //Actualiza la vida del castillo
            prepjuego.EliminarTropaCastillo(2);
            prepjuego.ReiniciaPosicionesCam();
            prepjuego.ActualizarIconoCam();
        }
    }

    public void interTropas() {

        if (prepjuego.verificaDueloTropas() == 1) {
            prepjuego.Combate(1);
            prepjuego.ActualizarIconoCam();
            prepjuego.ReiniciaPosicionesCam();
            if (prepjuego.CambioRonda()) {
                prepjuego.RandomCPU(Integer.parseInt(lblNumRonda.getText()));

                JOptionPane.showMessageDialog(null, "PREPÁRESE PARA LA SIGUIENTE RONDA \n ELIGE BIEN TUS TROPAS");
                btnMostrarTropas.setEnabled(true);
                btnOcultarTropas.setEnabled(true);
                hilo.interrupt();
   

            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJuego().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnMostrarTropas;
    private javax.swing.JButton btnOcultarTropas;
    private javax.swing.JLabel lblArqueraUI;
    public static javax.swing.JLabel lblCPU1;
    public static javax.swing.JLabel lblCPU2;
    public static javax.swing.JLabel lblCPU3;
    private javax.swing.JLabel lblCaballero;
    public static javax.swing.JLabel lblCantidadTropas;
    public static javax.swing.JLabel lblCastilloCPU;
    public static javax.swing.JLabel lblCastilloPlayer;
    private javax.swing.JLabel lblCorazonCpu;
    private javax.swing.JLabel lblCorazonPlayer;
    private javax.swing.JLabel lblMagoUI;
    private javax.swing.JLabel lblMapa;
    private javax.swing.JLabel lblNRonda;
    public static javax.swing.JLabel lblNumRonda;
    private javax.swing.JLabel lblTextCamino;
    private javax.swing.JLabel lblTextTropasRestantes;
    private javax.swing.JLabel lblTextTropasRestantes1;
    public static javax.swing.JLabel lblTropa1CPU;
    public static javax.swing.JLabel lblTropaPlayer1;
    public static javax.swing.JLabel lblVidasCpu;
    public static javax.swing.JLabel lblVidasPlayer;
    // End of variables declaration//GEN-END:variables
}
