package vista;

/**
 *
 * @author Angelo
 */
public class frmJuego extends javax.swing.JFrame {

    /**
     * Creates new form frmJuego
     */
    public frmJuego() {
        //Preparacion.lblNumRondaP.setText(lblNumRonda.getText());
        initComponents();
        setSize(1920, 1080); //Tamaño del frame
        setResizable(false); //Para no poder extender al frame
        setLocationRelativeTo(null); //Para que se muestre centrado

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNRonda = new javax.swing.JLabel();
        lblNumRonda = new javax.swing.JLabel();
        lblCastilloCPU = new javax.swing.JLabel();
        lblCastilloPlayer = new javax.swing.JLabel();
        lblTropa1CPU = new javax.swing.JLabel();
        lblTropa2CPU = new javax.swing.JLabel();
        lblTropaPlayer1 = new javax.swing.JLabel();
        lblTropaPlayer2 = new javax.swing.JLabel();
        lblVidasCpu = new javax.swing.JLabel();
        lblVidasPlayer = new javax.swing.JLabel();
        lblCorazonCpu = new javax.swing.JLabel();
        lblCorazonPlayer = new javax.swing.JLabel();
        lblMapa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNRonda.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblNRonda.setText("N° Ronda");
        getContentPane().add(lblNRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 170, 30));

        lblNumRonda.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblNumRonda.setText("1");
        getContentPane().add(lblNumRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 0, 40, 40));

        lblCastilloCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Castillo-rojo-x307.png"))); // NOI18N
        getContentPane().add(lblCastilloCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        lblCastilloPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Castillo-verde-x307.png"))); // NOI18N
        getContentPane().add(lblCastilloPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 360, -1, -1));
        getContentPane().add(lblTropa1CPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));
        getContentPane().add(lblTropa2CPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, -1, -1));
        getContentPane().add(lblTropaPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 440, -1, -1));
        getContentPane().add(lblTropaPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 570, -1, -1));

        lblVidasCpu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVidasCpu.setForeground(new java.awt.Color(255, 255, 255));
        lblVidasCpu.setText("10");
        lblVidasCpu.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblVidasCpuPropertyChange(evt);
            }
        });
        getContentPane().add(lblVidasCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 314, -1, -1));

        lblVidasPlayer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblVidasPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblVidasPlayer.setText("10");
        getContentPane().add(lblVidasPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1695, 314, -1, -1));

        lblCorazonCpu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCorazonCpu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Corazon.png"))); // NOI18N
        lblCorazonCpu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblCorazonCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 300, -1, -1));

        lblCorazonPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Corazon.png"))); // NOI18N
        getContentPane().add(lblCorazonPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1674, 300, -1, -1));

        lblMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TowerDefence.jpg"))); // NOI18N
        getContentPane().add(lblMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVidasCpuPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblVidasCpuPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_lblVidasCpuPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJuego().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel lblCastilloCPU;
    public static javax.swing.JLabel lblCastilloPlayer;
    private javax.swing.JLabel lblCorazonCpu;
    private javax.swing.JLabel lblCorazonPlayer;
    private javax.swing.JLabel lblMapa;
    private javax.swing.JLabel lblNRonda;
    public static javax.swing.JLabel lblNumRonda;
    public static javax.swing.JLabel lblTropa1CPU;
    public static javax.swing.JLabel lblTropa2CPU;
    public static javax.swing.JLabel lblTropaPlayer1;
    public static javax.swing.JLabel lblTropaPlayer2;
    public static javax.swing.JLabel lblVidasCpu;
    public static javax.swing.JLabel lblVidasPlayer;
    // End of variables declaration//GEN-END:variables
}
